name: Kong Gateway test
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  validate-code:
    name: Chekout 
    runs-on: ubuntu-latest

    steps:
      # Checkout Code
      - name: Checkout Code
        uses: actions/checkout@v4

      # Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      # Install dependecies
      - name: Install Dependencies
        run: npm install


      - name: Cypress Syntax Check
        run: npx cypress info

      - name: Upload Config Artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: project-configs
          path: |
            cypress.config.js
            package.json